# Generated by Django 2.2.11 on 2020-03-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0003_auto_20191021_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionedpicture',
            name='use_automatic_scaling',
            field=models.BooleanField(blank=True, default=True, help_text='Uses the placeholder dimensions to automatically calculate the size.', verbose_name='Automatic scaling'),
        ),
        migrations.AlterField(
            model_name='versionedpicture',
            name='use_crop',
            field=models.BooleanField(blank=True, default=False, help_text='Crops the image according to the thumbnail settings provided in the template.', verbose_name='Crop image'),
        ),
        migrations.AlterField(
            model_name='versionedpicture',
            name='use_no_cropping',
            field=models.BooleanField(blank=True, default=False, help_text='Outputs the raw image without cropping.', verbose_name='Use original image'),
        ),
        migrations.AlterField(
            model_name='versionedpicture',
            name='use_upscale',
            field=models.BooleanField(blank=True, default=False, help_text='Upscales the image to the size of the thumbnail settings in the template.', verbose_name='Upscale image'),
        ),
    ]
