# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-01 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileGrouper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'filer grouper',
                'verbose_name_plural': 'filer groupers',
            },
        ),
    ]
