# Generated by Django 2.2.14 on 2021-01-06 01:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_versioning_filer', '0002_file_grouper'),
    ]

    operations = [
        migrations.AddField(
            model_name='filegrouper',
            name='canonical_created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filegrouper',
            name='canonical_file_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
