# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangocms_attributes_field.fields
import djangocms_versioning_filer.fields.file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djangocms_versioning_filer', '0002_file_grouper'),
        ('cms', '0034_remove_pagecontent_placeholders'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionedFile',
            fields=[
                ('template', models.CharField(choices=[('default', 'Default')], default='default', max_length=255, verbose_name='Template')),
                ('file_name', models.CharField(blank=True, help_text='Overrides the default file name with the given value.', max_length=255, verbose_name='Name')),
                ('link_target', models.CharField(blank=True, choices=[('_self', 'Open in same window'), ('_blank', 'Open in new window'), ('_parent', 'Delegate to parent'), ('_top', 'Delegate to top')], default='', max_length=255, verbose_name='Link target')),
                ('link_title', models.CharField(blank=True, max_length=255, verbose_name='Link title')),
                ('show_file_size', models.BooleanField(default=False, help_text='Appends the file size at the end of the name.', verbose_name='Show file size')),
                ('attributes', djangocms_attributes_field.fields.AttributesField(blank=True, default=dict, verbose_name='Attributes')),
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='file_versionedfile', serialize=False, to='cms.CMSPlugin')),
                ('file_grouper', djangocms_versioning_filer.fields.file.FileGrouperField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='djangocms_versioning_filer.FileGrouper', verbose_name='File grouper')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
