# Generated by Django 2.2.11 on 2020-03-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionedfile',
            name='show_file_size',
            field=models.BooleanField(blank=True, default=False, help_text='Appends the file size at the end of the name.', verbose_name='Show file size'),
        ),
    ]
